version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: goodbooks_postgres
    restart: always
    environment:
      POSTGRES_USER: maria
      POSTGRES_PASSWORD: maria_password
      POSTGRES_DB: goodbooks
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: